title: Take part in the Coolest Projects Web Category
hero_image: images/banner.png
description: Enter Coolest Projects with a web page or web site.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Take part in the Coolest Projects Web Category
