title: Take part in the Coolest Projects Web category
hero_image: images/banner.png
description: Enter Coolest Projects with a webpage or website.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Take part in the Coolest Projects Web category
